const phrases = new Map(Object.entries({
  "Admin Dashboard":"অ্যাডমিন ড্যাশবোর্ড","Customer Dashboard":"গ্রাহক ড্যাশবোর্ড","Partner Dashboard":"সেবাদাতা ড্যাশবোর্ড",
  "Site Content":"ওয়েবসাইটের বিষয়বস্তু","Service Catalog":"সেবার তালিকা","Partner Review":"সেবাদাতা যাচাই","Bookings and Assignment":"বুকিং ও দায়িত্ব প্রদান",
  "Cancellation and Rejection Requests":"বাতিল ও প্রত্যাখ্যানের আবেদন","Booking Fees":"বুকিং ফি","Work Payments":"কাজের পারিশ্রমিক","Customer Management":"গ্রাহক ব্যবস্থাপনা","Partner Management":"সেবাদাতা ব্যবস্থাপনা","Support Messages":"সহায়তার বার্তা","Withdrawal Requests":"টাকা তোলার আবেদন",
  "Current Orders":"চলমান কাজ","Order History":"কাজের ইতিহাস","Previous Orders":"আগের কাজ","Final Work Payments":"চূড়ান্ত কাজের পারিশ্রমিক","Wallet and Withdraw":"ওয়ালেট ও টাকা উত্তোলন",
  "Change Partner":"সেবাদাতা পরিবর্তন","Request Cancellation":"বাতিলের আবেদন","Request Job Rejection":"কাজ প্রত্যাখ্যানের আবেদন","Security":"নিরাপত্তা","Profile":"প্রোফাইল","Notifications":"বিজ্ঞপ্তি","Overview":"সারসংক্ষেপ",
  "Add New Service":"নতুন সেবা যোগ করুন","Existing Services":"বর্তমান সেবাসমূহ","Save Changes":"পরিবর্তন সংরক্ষণ","View Details":"বিস্তারিত দেখুন","Approve Payment":"পরিশোধ অনুমোদন","Approve":"অনুমোদন করুন","Reject Request":"আবেদন প্রত্যাখ্যান","Mark Paid":"পরিশোধিত করুন",
  "Payment Pending":"পরিশোধ অপেক্ষমাণ","In Progress":"কাজ চলছে","Not assigned":"দায়িত্ব দেওয়া হয়নি","Waiting for admin":"অ্যাডমিনের অপেক্ষায়","No records found.":"কোনো তথ্য পাওয়া যায়নি।",
  "Website Language":"ওয়েবসাইটের ভাষা","Switch the entire website language":"সম্পূর্ণ ওয়েবসাইটের ভাষা পরিবর্তন করুন","Light":"আলো","Dark":"অন্ধকার",
  "Login / Signup":"প্রবেশ / নিবন্ধন","Admin Login":"অ্যাডমিন প্রবেশ","Customer Login":"গ্রাহক প্রবেশ","Partner Login":"সেবাদাতা প্রবেশ","Create Account":"হিসাব খুলুন","Change Password":"গোপন শব্দ পরিবর্তন","Forgot Password":"গোপন শব্দ ভুলে গেছেন",
  "Previous":"আগের","Next":"পরের","Clear":"মুছুন","Search":"খুঁজুন","Cancel":"বাতিল","Close":"বন্ধ করুন","Edit":"সম্পাদনা","Delete":"মুছুন","Remove":"সরান","Refresh Data":"তথ্য হালনাগাদ","Logout":"লগআউট","Dashboard":"ড্যাশবোর্ড"
}));

Object.entries({
  "Something went wrong":"কিছু সমস্যা হয়েছে","Reload Page":"পৃষ্ঠা আবার খুলুন","Return Home":"হোমে ফিরুন","No messages yet.":"এখনও কোনো বার্তা নেই।","No messages found.":"কোনো বার্তা পাওয়া যায়নি।",
  "About Us":"আমাদের সম্পর্কে","Our Team":"আমাদের দল","Privacy Policy":"গোপনীয়তা নীতি","Terms & conditions":"শর্তাবলি","Know More":"আরও জানুন","Newsletter":"সংবাদপত্র","Call Us":"ফোন করুন","Email Now":"ইমেইল করুন","Find us":"আমাদের খুঁজুন","Login now":"এখন প্রবেশ করুন",
  "Quick Actions":"দ্রুত কাজ","Quick Open":"দ্রুত খুলুন","Snapshot":"এক নজরে","Active Orders":"চলমান কাজসমূহ","Assigned Chats":"নির্ধারিত কথোপকথন","Live Chat":"সরাসরি কথোপকথন","Open Current Orders":"চলমান কাজ খুলুন","Open Payments":"পরিশোধ খুলুন","Open Orders":"কাজসমূহ খুলুন","Open Wallet":"ওয়ালেট খুলুন",
  "Book New Service":"নতুন সেবা বুক করুন","Browse New Partner":"নতুন সেবাদাতা খুঁজুন","Choose a New Partner":"নতুন সেবাদাতা বেছে নিন","Change Partner or Cancel Booking":"সেবাদাতা পরিবর্তন অথবা বুকিং বাতিল","Request History":"আবেদনের ইতিহাস","Request Cancel":"বাতিলের আবেদন","Request Reject":"প্রত্যাখ্যানের আবেদন","Send Request":"আবেদন পাঠান",
  "Payment History":"পরিশোধের ইতিহাস","Submit Payment":"পরিশোধ জমা দিন","Verify Final Amount":"চূড়ান্ত পরিমাণ যাচাই করুন","Rate Now":"এখন মূল্যায়ন করুন","Submit Rating":"মূল্যায়ন জমা দিন","Rating Notifications":"মূল্যায়নের বিজ্ঞপ্তি","Rate Completed Jobs":"সম্পন্ন কাজের মূল্যায়ন",
  "No current orders.":"কোনো চলমান কাজ নেই।","No previous orders yet.":"এখনও আগের কোনো কাজ নেই।","No active orders.":"কোনো সক্রিয় কাজ নেই।","No completed orders yet.":"এখনও কোনো সম্পন্ন কাজ নেই।","No payment records yet.":"এখনও কোনো পরিশোধের তথ্য নেই।","No support messages yet.":"এখনও কোনো সহায়তার বার্তা নেই।","No wallet records yet.":"এখনও কোনো ওয়ালেট তথ্য নেই।","No rejection requests yet.":"এখনও কোনো প্রত্যাখ্যানের আবেদন নেই।","No cancellation requests yet.":"এখনও কোনো বাতিলের আবেদন নেই।",
  "Save Profile":"প্রোফাইল সংরক্ষণ","Edit Profile":"প্রোফাইল সম্পাদনা","Profile Edit":"প্রোফাইল সম্পাদনা","Save Working Time":"কাজের সময় সংরক্ষণ","Update Availability":"উপলভ্যতা হালনাগাদ","Request Withdraw":"টাকা তোলার আবেদন","Withdrawal Wallet":"উত্তোলনের ওয়ালেট","Payment Method":"পরিশোধের পদ্ধতি","Account Holder Name":"হিসাবধারীর নাম","Bank Account":"ব্যাংক হিসাব","Bank Name":"ব্যাংকের নাম","Branch Name":"শাখার নাম","Routing Number (optional)":"রাউটিং নম্বর (ঐচ্ছিক)",
  "Booking Fee Records":"বুকিং ফির তথ্য","Fee Status":"ফির অবস্থা","Payment Details":"পরিশোধের বিস্তারিত","Status / Action":"অবস্থা / কাজ","Request Type":"আবেদনের ধরন","Booking / Requester":"বুকিং / আবেদনকারী","Review Change Request":"পরিবর্তনের আবেদন পর্যালোচনা","Open submitted proof":"জমা দেওয়া প্রমাণ খুলুন","Pending Partner Review":"অপেক্ষমাণ সেবাদাতা যাচাই","Booking Details":"বুকিংয়ের বিস্তারিত","Service Card Image":"সেবার কার্ডের ছবি","Service Key":"সেবার চাবি","Service Title":"সেবার শিরোনাম","Homepage Reviews":"হোমপেজের পর্যালোচনা","Home Hero":"হোমের প্রধান অংশ","Promo Section":"প্রচার অংশ","Contact Details":"যোগাযোগের তথ্য","Why Choose Us":"আমাদের কেন বেছে নেবেন",
  "Customer Signup":"গ্রাহক নিবন্ধন","Partner Signup":"সেবাদাতা নিবন্ধন","Full Name":"পূর্ণ নাম","Email or Mobile":"ইমেইল অথবা মুঠোফোন","Email, Mobile, or Partner Code":"ইমেইল, মুঠোফোন অথবা সেবাদাতা কোড","Service Info":"সেবার তথ্য","Personal":"ব্যক্তিগত তথ্য","Documents":"কাগজপত্র","Verification Documents":"যাচাইয়ের কাগজপত্র","Technician Category":"সেবার বিভাগ","Current Service Area":"বর্তমান সেবার এলাকা","Profile Photo":"প্রোফাইলের ছবি","NID Front Photo":"জাতীয় পরিচয়পত্রের সামনের ছবি","NID Back Photo":"জাতীয় পরিচয়পত্রের পেছনের ছবি","NID Number":"জাতীয় পরিচয়পত্র নম্বর","NID Address":"জাতীয় পরিচয়পত্রের ঠিকানা","Father Name":"বাবার নাম","Mother Name":"মায়ের নাম","First Name (as NID)":"নামের প্রথম অংশ (পরিচয়পত্র অনুযায়ী)","Last Name (as NID)":"নামের শেষ অংশ (পরিচয়পত্র অনুযায়ী)","No file selected":"কোনো ফাইল বাছাই করা হয়নি",
  "Page not found.":"পৃষ্ঠা পাওয়া যায়নি।","Go Home":"হোমে যান","Book Now":"এখনই বুক করুন","View All Services":"সব সেবা দেখুন","Popular categories":"জনপ্রিয় বিভাগ","Featured services":"বিশেষ সেবাসমূহ","Trusted service":"বিশ্বস্ত সেবা","Customer stories":"গ্রাহকের অভিজ্ঞতা","Right Technician":"সঠিক সেবাদাতা","Trust & Safety":"বিশ্বাস ও নিরাপত্তা","Eco-friendly":"পরিবেশবান্ধব"
}).forEach(([key,value])=>phrases.set(key,value));

Object.entries({
  "Enter ward number":"ওয়ার্ড নম্বর লিখুন","Morning / 2 PM / Evening":"সকাল / দুপুর ২টা / সন্ধ্যা","Enter your password":"আপনার গোপন শব্দ লিখুন","Current password":"বর্তমান গোপন শব্দ","New password":"নতুন গোপন শব্দ","Optional feedback":"ঐচ্ছিক মতামত","Explain why you need to cancel":"কেন বাতিল করতে চান তা লিখুন","Write your message to admin":"অ্যাডমিনকে আপনার বার্তা লিখুন","Booking ID or customer name":"বুকিং নম্বর অথবা গ্রাহকের নাম","Booking ID or customer":"বুকিং নম্বর অথবা গ্রাহক","Refund note":"ফেরতের মন্তব্য","First name":"নামের প্রথম অংশ","Last name":"নামের শেষ অংশ","NID address":"জাতীয় পরিচয়পত্রের ঠিকানা","NID number":"জাতীয় পরিচয়পত্র নম্বর","Father name":"বাবার নাম","Mother name":"মায়ের নাম",
  "Edit homepage hero text, promo images, contact information, address, and about-page copy.":"হোমের প্রধান লেখা, প্রচারের ছবি, যোগাযোগ, ঠিকানা ও পরিচিতির তথ্য সম্পাদনা করুন।","Update this section and save your changes.":"এই অংশ হালনাগাদ করে পরিবর্তন সংরক্ষণ করুন।","Edit the three homepage trust points.":"হোমপেজের তিনটি আস্থার বিষয় সম্পাদনা করুন।","Seven cards are shown in the animated review row.":"চলমান পর্যালোচনা সারিতে সাতটি কার্ড দেখানো হয়।","Manage the services available throughout the website.":"সম্পূর্ণ ওয়েবসাইটে থাকা সেবাসমূহ পরিচালনা করুন।","The customer-selected partner is preselected for quick assignment.":"দ্রুত দায়িত্ব দেওয়ার জন্য গ্রাহকের নির্বাচিত সেবাদাতা আগে থেকেই বাছাই করা আছে।","Customer cancellation approval refunds the booking fee. Partner rejection approval returns the booking for reassignment.":"গ্রাহকের বাতিলের আবেদন অনুমোদন করলে বুকিং ফি ফেরত যায়। সেবাদাতার প্রত্যাখ্যান অনুমোদন করলে বুকিংটি আবার দায়িত্ব দেওয়ার জন্য প্রস্তুত হয়।","Newest records appear first.":"সর্বশেষ তথ্য প্রথমে দেখানো হয়।","Edit profile, update active status, or remove account.":"প্রোফাইল সম্পাদনা, সক্রিয় অবস্থা পরিবর্তন অথবা হিসাব সরান।","Edit profile, update verification or availability, and remove account.":"প্রোফাইল, যাচাই ও উপলভ্যতা হালনাগাদ অথবা হিসাব সরান।","Reply to customers and partners from here.":"এখান থেকে গ্রাহক ও সেবাদাতাকে উত্তর দিন।","Used across the website.":"সম্পূর্ণ ওয়েবসাইটে ব্যবহৃত হয়।",
  "Profile, orders, payments, and chat in focused sidebar sections.":"প্রোফাইল, কাজ, পরিশোধ ও কথোপকথন আলাদা অংশে সাজানো আছে।","Profile, availability, orders, wallet, and chat in focused sidebar sections.":"প্রোফাইল, উপলভ্যতা, কাজ, ওয়ালেট ও কথোপকথন আলাদা অংশে সাজানো আছে।","This booking already has a request waiting for admin review.":"এই বুকিংয়ের একটি আবেদন অ্যাডমিনের পর্যালোচনার অপেক্ষায় আছে।","Both free partner changes have already been used.":"দুটি বিনামূল্যের সেবাদাতা পরিবর্তন ইতিমধ্যে ব্যবহার করা হয়েছে।","You verified the final amount. Partner change now requires a new paid booking.":"আপনি চূড়ান্ত পরিমাণ যাচাই করেছেন। এখন সেবাদাতা বদলাতে নতুন ফিসহ বুকিং প্রয়োজন।","No approved partners are listed for this category.":"এই বিভাগে কোনো অনুমোদিত সেবাদাতা নেই।","Verify the final amount agreed with your partner. Payment will open immediately after confirmation.":"সেবাদাতার সঙ্গে নির্ধারিত চূড়ান্ত পরিমাণ যাচাই করুন। নিশ্চিত করার পর পরিশোধ চালু হবে।",
  "Booking fees belong to the platform admin and are never added to this wallet.":"বুকিং ফি প্ল্যাটফর্ম অ্যাডমিনের এবং এই ওয়ালেটে যোগ হয় না।","Add bKash, Nagad, Rocket, or bank account details before requesting a withdrawal.":"টাকা তোলার আগে বিকাশ, নগদ, রকেট অথবা ব্যাংক হিসাব যোগ করুন।","No work earnings yet. Your wallet will be credited after an approved final payment and completed job.":"এখনও কাজের আয় নেই। চূড়ান্ত পরিশোধ অনুমোদন ও কাজ সম্পন্ন হলে ওয়ালেটে টাকা যোগ হবে।","Admin will send approved withdrawals to this account.":"অনুমোদিত উত্তোলনের টাকা অ্যাডমিন এই হিসাবে পাঠাবেন।","Your request is waiting for admin review. This job cannot be completed meanwhile.":"আপনার আবেদন অ্যাডমিনের পর্যালোচনার অপেক্ষায় আছে। এই সময় কাজটি সম্পন্ন করা যাবে না।","No assigned job is currently eligible for rejection.":"প্রত্যাখ্যানের উপযুক্ত কোনো নির্ধারিত কাজ নেই।",
  "Access partner verification panel.":"সেবাদাতা যাচাই বিভাগে প্রবেশ করুন।","Use your mobile, email, or approved partner code to login.":"মুঠোফোন, ইমেইল অথবা অনুমোদিত সেবাদাতা কোড দিয়ে প্রবেশ করুন।","Use email or mobile number.":"ইমেইল অথবা মুঠোফোন নম্বর ব্যবহার করুন।","Minimum 6 characters.":"কমপক্ষে ৬টি অক্ষর লিখুন।","Must be unique for verification.":"যাচাইয়ের জন্য এটি অবশ্যই স্বতন্ত্র হতে হবে।","Used for login and contact.":"প্রবেশ ও যোগাযোগের জন্য ব্যবহৃত হবে।"
}).forEach(([key,value])=>phrases.set(key,value));

const words = {Home:"হোম",Services:"সেবাসমূহ",About:"পরিচিতি",Contact:"যোগাযোগ",Admin:"অ্যাডমিন",Customer:"গ্রাহক",Partner:"সেবাদাতা",Booking:"বুকিং",Bookings:"বুকিংসমূহ",Service:"সেবা",Payment:"পরিশোধ",Payments:"পরিশোধসমূহ",Fee:"ফি",Amount:"পরিমাণ",Status:"অবস্থা",Action:"কাজ",Name:"নাম",Mobile:"মুঠোফোন",Email:"ইমেইল",Address:"ঠিকানা",Date:"তারিখ",Category:"বিভাগ",Area:"এলাকা",District:"জেলা",Thana:"থানা",Ward:"ওয়ার্ড",Reason:"কারণ",Proof:"প্রমাণ",Note:"মন্তব্য",Details:"বিস্তারিত",Request:"আবেদন",Requests:"আবেদনসমূহ",Pending:"অপেক্ষমাণ",Assigned:"দায়িত্বপ্রাপ্ত",Approved:"অনুমোদিত",Rejected:"প্রত্যাখ্যাত",Completed:"সম্পন্ন",Paid:"পরিশোধিত",Available:"উপলভ্য",Busy:"ব্যস্ত",Active:"সক্রিয়",Inactive:"নিষ্ক্রিয়",Save:"সংরক্ষণ",Submit:"জমা দিন",Update:"হালনাগাদ",Add:"যোগ করুন",New:"নতুন",View:"দেখুন",Review:"পর্যালোচনা",Verify:"যাচাই",Assign:"দায়িত্ব দিন",Refund:"ফেরত",Withdraw:"উত্তোলন",Wallet:"ওয়ালেট",History:"ইতিহাস",Messages:"বার্তা",Message:"বার্তা",Chat:"কথোপকথন",Support:"সহায়তা",Settings:"সেটিংস",Content:"বিষয়বস্তু",Title:"শিরোনাম",Description:"বিবরণ",Image:"ছবি",Upload:"আপলোড",Password:"গোপন শব্দ",Current:"বর্তমান",Previous:"আগের",Next:"পরের",Page:"পৃষ্ঠা",of:"এর",Search:"খুঁজুন",Filter:"ছাঁকনি",All:"সব",Total:"মোট",Revenue:"আয়",Language:"ভাষা",English:"ইংরেজি",Bangla:"বাংলা",Open:"খুলুন",Send:"পাঠান",Select:"বেছে নিন",Type:"ধরন",Code:"কোড",Account:"হিসাব",Method:"পদ্ধতি",Working:"কাজের",Hours:"সময়",Experience:"অভিজ্ঞতা",Rating:"মূল্যায়ন",Today:"আজ",Online:"অনলাইন",Manual:"হাতে",Final:"চূড়ান্ত",Work:"কাজ",Order:"কাজ",Orders:"কাজসমূহ",Management:"ব্যবস্থাপনা",Records:"তথ্যসমূহ",Information:"তথ্য"};

Object.assign(words,{Login:"প্রবেশ",Signup:"নিবন্ধন",Logout:"লগআউট",Create:"তৈরি করুন",Confirm:"নিশ্চিত করুন",Choose:"বেছে নিন",Browse:"খুঁজুন",Change:"পরিবর্তন",Cancel:"বাতিল",Close:"বন্ধ করুন",Complete:"সম্পন্ন করুন",Offline:"অফলাইন",Availability:"উপলভ্যতা",Verification:"যাচাই",Balance:"জমা",Bank:"ব্যাংক",Branch:"শাখা",Routing:"রাউটিং",Number:"নম্বর",Holder:"ধারী",Optional:"ঐচ্ছিক",Profile:"প্রোফাইল",Photo:"ছবি",Photos:"ছবিসমূহ",Document:"কাগজপত্র",Documents:"কাগজপত্র",Identity:"পরিচয়",Personal:"ব্যক্তিগত",Father:"বাবা",Mother:"মা",First:"প্রথম",Last:"শেষ",Start:"শুরু",End:"শেষ",Time:"সময়",Preferred:"পছন্দের",Expected:"প্রত্যাশিত",Cash:"নগদ",Charge:"ফি",Problem:"সমস্যা",Extra:"অতিরিক্ত",Company:"প্রতিষ্ঠান",Team:"দল",Privacy:"গোপনীয়তা",Terms:"শর্তাবলি",Policy:"নীতি",Newsletter:"সংবাদপত্র",Loading:"লোড হচ্ছে",Error:"সমস্যা",Unknown:"অজানা",None:"কোনোটিই নয়",Reply:"উত্তর",Quick:"দ্রুত",Actions:"কাজসমূহ",Summary:"সারসংক্ষেপ",Count:"সংখ্যা",Recent:"সাম্প্রতিক",Newest:"সর্বশেষ",Results:"ফলাফল",Result:"ফলাফল",More:"আরও",Back:"ফিরুন",Continue:"এগিয়ে যান",Next:"পরের",Previous:"আগের",Download:"নামান",Print:"মুদ্রণ",Location:"অবস্থান",Role:"ভূমিকা",Text:"লেখা",Button:"বোতাম",Link:"সংযোগ",Hero:"প্রধান অংশ",Kicker:"শুরুর লেখা",Badge:"চিহ্ন",Strip:"তথ্যসারি",Mission:"লক্ষ্য",Vision:"দূরদর্শিতা",Promo:"প্রচার",Review:"পর্যালোচনা",Reviews:"পর্যালোচনাসমূহ",Homepage:"হোমপেজ",Website:"ওয়েবসাইট",System:"ব্যবস্থা",Secure:"নিরাপদ",Modern:"আধুনিক",Trusted:"বিশ্বস্ত",Technician:"সেবাদাতা",Technicians:"সেবাদাতারা",Professional:"পেশাজীবী",Professionals:"পেশাজীবীরা",bKash:"বিকাশ",Nagad:"নগদ",Rocket:"রকেট",TrxID:"লেনদেন নম্বর"});

const transliteration={a:"আ",b:"ব",c:"ক",d:"দ",e:"এ",f:"ফ",g:"গ",h:"হ",i:"ই",j:"জ",k:"ক",l:"ল",m:"ম",n:"ন",o:"ও",p:"প",q:"ক",r:"র",s:"স",t:"ট",u:"উ",v:"ভ",w:"ও",x:"ক্স",y:"য়",z:"জ"};
Object.assign(words,{Mistri:"Mistri",Chai:"Chai",MistriChai:"MistriChai"});
function banglaScript(word) { return [...word.toLowerCase()].map((letter)=>transliteration[letter] || letter).join(""); }
function shouldPreserve(text) { return /(?:https?:\/\/|www\.|\S+@\S+|\b01\d{9}\b|\b[A-Z]{2,}[-_]?\d+\b|\b\w*\d\w*\b)/.test(text); }
function looksLikeProperName(text) {
  const parts=text.trim().split(/\s+/);
  return parts.length >= 2 && parts.length <= 4
    && parts.every((part)=>/^[A-Z][a-z.'-]+$/.test(part))
    && !parts.some((part)=>words[part]);
}

export function toBanglaUi(value) {
  const text=String(value || "");
  const trimmed=text.trim();
  if (!trimmed || !/[A-Za-z]/.test(trimmed)) return text;
  if (phrases.has(trimmed)) return text.replace(trimmed,phrases.get(trimmed));
  if (/^[A-Z_]+$/.test(trimmed)) return trimmed.split("_").map((word)=>words[word.charAt(0)+word.slice(1).toLowerCase()] || word).join(" ");
  if (shouldPreserve(trimmed) || looksLikeProperName(trimmed)) return text.replace(/\b[A-Za-z]+\b/g,(word)=>words[word] || words[word.charAt(0).toUpperCase()+word.slice(1).toLowerCase()] || word);
  return text.replace(/\b[A-Za-z]+\b/g,(word)=>words[word] || words[word.charAt(0).toUpperCase()+word.slice(1).toLowerCase()] || banglaScript(word));
}

export function translateUiTree(root=document.body) {
  if (!root) return;
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach((node)=>{ if (["SCRIPT","STYLE"].includes(node.parentElement?.tagName)) return; const next=toBanglaUi(node.nodeValue); if(next!==node.nodeValue) node.nodeValue=next; });
  root.querySelectorAll?.("[placeholder],[title],[aria-label]").forEach((element)=>["placeholder","title","aria-label"].forEach((attr)=>{ if(element.hasAttribute(attr)) element.setAttribute(attr,toBanglaUi(element.getAttribute(attr))); }));
}
